### ISSUE TITLE
line 1: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by ikenna** [NickHeap2/add-props-flipflop#1]
Problem:

1. Cloned repo on my mac
2. Ran `npm install -g`
3. Ran script `add-props-flipflop --help`
4. Got error `/Users/ikenna/.asdf/installs/nodejs/19.2.0/bin/add-props-flipflop: line 1: syntax error near unexpected token `('
/Users/ikenna/.asdf/installs/nodejs/19.2.0/bin/add-props-flipflop: line 1: `const fs = require('fs')`

I suspect the problem may be because `https://github.com/NickHeap2/add-props-flipflop/blob/main/lib/index.js` does not start with `#!/usr/bin/env node` ?

**Comment by NickHeap2** [comment]
Have merged your PR let me know if that resolves things.

**Comment by ikenna** [comment]
Looks good. Thanks @NickHeap2 👍 .
